### ISSUE TITLE
Update BusinessLogic class to reflect DrinkMixingMachine class

### ISSUE THREAD

**Issue by DavidFederl** [ES-EDU-SIEGMA/User-Interface#28]
- [x] #50
- [x] #51
- [x] Make use of `Data` instead of `DataInterface`
- [x] Move State machine from UI classes to `DrinkMixingMachine`

---

Depends on
- #36 
- #29 
- #33 
- #30

**Comment by kamilloo1** [comment]
As discussed, the "get_configration()" method should be implemented in the business logic and not in the data class.
