### ISSUE TITLE
Add Drink/Ingredient Datatypes

### ISSUE THREAD

**Issue by DavidFederl** [ES-EDU-SIEGMA/User-Interface#38]
- [x] Add class `Ingredient`
- [x] Add class `Drink`

---

Depends on
- NOTHING

**Comment by kamilloo1** [comment]
- get_timing array zurückgeben
- hopper_id mit none als Datentyp
- unit-Tests für Drink und Ingredient
- Konstruktor für Drink
- Fehlerbehandlung wegen 100 %
- Konstruktor in der Übersicht ergänzen für Drink und Integrient

**Comment by DavidFederl** [comment]
get_timing should not be in here => it's hardware depending and should stay in the hardware library as a Calculator (see #34)

**Comment by kamilloo1** [comment]
Hey could you explain what is meant with hopper_id please @DavidFederl ? Why do weed need this in the Ingredient class?

**Comment by DavidFederl** [comment]
> Hey could you explain what is meant with hopper_id please [@DavidFederl](https://github.com/DavidFederl) ? Why do weed need this in the Ingredient class?

It is meant to store the hopper associated with the ingredient. So either a positive Integer or None.

**Comment by kamilloo1** [comment]
And if there are more hopper with the same ingredient?

**Comment by DavidFederl** [comment]
## Examples

### ingredients

```JSON
{
    "ingredients": [  
      {  
        "id": 0,  
        "name": "jjj",  
        "flow_speed": 1,  
        "dispenser_id": 22  
      },  
      {  
        "id": 1,  
        "name": "xxx",  
        "flow_speed": 1,  
        "dispenser_id": 44  
      },
      ...
    ]
}
```

### recipes

```JSON
{
  "drinks": [
    {
      "id": 0,
      "name": "jjj",
      "ingredients": [
          {
              "id": 0,
              "percentage": 10
          },
          {
              "id": 1,
              "percentage": 90
          }
      ]
    }, 
    {
      "id": 1,
      "name": "xxx",
      "ingredients": [
          {
              "id": 0,
              "percentage": 50
          },
          {
              "id": 1,
              "percentage": 50
          }
      ]
    },
    ...
  ]
}
```

### config

> Path to `config.json` passed as CLI argument to the application!

```JSON
{
  "sources": {
    "drinks": "path/to/drinks.json",
    "recipes": "path/to/recipes.json"
  },
  "scale": {
    "measurements_per_value": 3,
    "wait_timeout": 3
  },
  "dispenser": {
    "glass_size": 250,
    "ms_per_ml": 100,
    "hopper_size": [
      40,
      40,
      ...
    ]
  },
  "serial": {
    "max_connection_attempts": 5
    "identifier": [
      "LEFT",
      "RIGHT",
      "RONDELL"
    ],
    "port": [
      "/dev/ttyACM0",
      "/dev/ttyACM1",
      "/dev/ttyACM2",
    ],
  }
}
```
