### ISSUE TITLE
Add JsonDatahandler alongside the Datahandler interface

### ISSUE THREAD

**Issue by DavidFederl** [ES-EDU-SIEGMA/User-Interface#39]
- [x]  Add `Datahandler` Interface
    - add class `Datahandler`
    - add functions from graph with `raise Exception("Not Implemented!)`
- [x] Add `JsonDatahandler`
    - implement functions from `Datahandler` interface 

---

Depends on
- #38

**Comment by DavidFederl** [comment]
For the Datahander interface class I would suggest somthing like:

```Python
import abc
import Ingredient
import Drink

class DatahandlerInterface(metaclass=abc.ABCMeta):
    @classmethod
    def __subclasshook__(cls, subclass):
        return (hassattr(subclass, 'read_ingredients') and
                callable(subclass.read_ingredients) and
                hassattr(subclass, 'write_ingredients') and
                callable(subclass.write_ingredients) and
                hassattr(subclass, 'read_drinks') and
                callable(subclass.read_drinks) and
                hassattr(subclass, 'write_drinks') and
                callable(subclass.write_drinks) or
                NotImplemented)

    @abc.abstractmethod
    def read_ingredients(self) -> list[Ingredient]:
        raise NotImplementedError

    @abc.abstractmethod
    ...
```

**Comment by DavidFederl** [comment]
Other class ´JsonDatahandler´ would then look like:

```Python
import DatahandlerInterface

class JsonDatahandler(Datahandlerinterface):
    ....
```

**Comment by kamilloo1** [comment]
In the read_ingredients function from the JsonDatahandler class, do I have to create a separate ingredient object for each ingredient from the JSON file? 

And what would be the best way to name the objects?

**Comment by DavidFederl** [comment]
> In the read_ingredients function from the JsonDatahandler class, do I have to create a separate ingredient object for each ingredient from the JSON file?
> 
> And what would be the best way to name the objects?

I would assume so. I guess it should look something like this:
```python
# load/parse json file
with open("path/to/file","r") as datasource:
    ingredients_dict = json.load(datasource)

# convert dictionary to list
ingredients: list[Ingredient] = []
for key, item in ingredients_dict:
    ingredients.append(Ingredient(id = key, name=item["name"], ...)

# return result
return ingredients
```
